### model
model_name_or_path: ${PROJECT_PATH}/model/qwen3-4b
# trust_remote_code: true

dataset: wisesight_sentiment 
template: qwen3
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 32
dataset_dir : ${PROJECT_PATH}/script
tokenized_path: ${PROJECT_PATH}/dataset/tokenized_dataset/wisesight_sentiment

### output
output_dir: ${PROJECT_PATH}/dataset/tokenized_dataset/wisesight_sentiment
overwrite_output_dir: true
